import Anthropic from '@anthropic-ai/sdk';
import { promises as fs } from 'fs';
import * as path from 'path';
import { glob } from 'glob';

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_KEY || '',
});

async function readFiles(pattern: string): Promise<string> {
  const files = await glob(pattern, { ignore: ['**/node_modules/**', '**/dist/**', '**/*.test.ts', '**/*.test.tsx'] });
  let content = '';
  for (const file of files) {
    try {
      const fileContent = await fs.readFile(file, 'utf-8');
      content += `\n\n--- File: ${file} ---\n\n${fileContent}`;
    } catch (e) {
      console.warn(`Could not read ${file}:`, e);
    }
  }
  return content;
}

const ARCHITECTURE_PROMPT = `You are a Principal Software Architect specialized in concurrency, systemic architectures, and the Deep Tree Echo architecture.
Your goal is to optimize the Sys6 Triality and Dove9 packages for better performance, clarity, and adherence to the inverted mirror MCP architecture.
Analyze the following code constraints and identify ANY bottlenecks, anti-patterns, or architectural flaws. Provide concrete code rewritten for maximum optimization.`;

const PERFORMANCE_PROMPT = `You are a Senior Frontend Performance Engineer specialized in WebGPU, React, and high-performance UI components.
Your goal is to optimize the frontend rendering pipeline, mitigate React re-renders, and optimize WebGPU latent space representations.
Analyze the provided code and suggest specific optimizations, code rewrites, or architectural changes to achieve 60+ FPS rendering of the AI Companion Hub.`;

const MEMORY_PROMPT = `You are a Senior Database Engineer and AI Memory Specialist specialized in DuckDB WASM, vector databases, and RAG.
Your goal is to optimize the hyperdimensional memory and reasoning kernel latency.
Review the provided reasoning and memory systems code, find heavy queries, suboptimal indexing strategies, or inefficient WASM/JS boundary crossings, and provide complete refactored methods.`;

async function runAgent(name: string, prompt: string, filePatterns: string[]): Promise<string> {
  console.log(`\n🤖 Starting ${name} Agent analysis...`);
  
  let codeContext = '';
  for (const pattern of filePatterns) {
    codeContext += await readFiles(pattern);
  }

  if (codeContext.length > 500000) {
    console.warn(`Context too large (${codeContext.length} chars). Truncating...`);
    codeContext = codeContext.slice(0, 500000);
  }

  if (codeContext.length === 0) {
      console.log(`No files found for ${name} Agent.`);
      return `### ${name} Agent Findings\n\nNo relevant files found to analyze.\n`;
  }

  const response = await anthropic.messages.create({
    model: 'claude-3-5-sonnet-20241022',
    max_tokens: 4000,
    system: prompt,
    messages: [
      {
        role: 'user',
        content: `Here is the codebase context to analyze:\n\n${codeContext}\n\nPlease provide your detailed optimization recommendations and code changes. Output valid Markdown.`
      }
    ]
  });

  const textContent = response.content.find(c => c.type === 'text');
  
  return `## ${name} Agent Findings\n\n${textContent ? textContent.text : 'No output'}\n\n`;
}

async function main() {
  if (!process.env.ANTHROPIC_KEY) {
    console.error('Error: ANTHROPIC_KEY environment variable is missing.');
    process.exit(1);
  }

  console.log('🚀 Deploying Deploy Optimization Agents...');
  let fullReport = '# Deep Tree Echo Optimization Report\n\nGenerated by Specialized AI Agents.\n\n';

  try {
    const archResults = await runAgent('Architecture', ARCHITECTURE_PROMPT, [
      'packages/sys6-triality/**/*.ts',
      'packages/dove9/**/*.ts',
      'packages/mcp/**/*.ts'
    ]);
    fullReport += archResults;

    const perfResults = await runAgent('Performance', PERFORMANCE_PROMPT, [
      'packages/frontend/src/components/**/*.ts',
      'packages/frontend/src/components/**/*.tsx',
      'packages/integrations/src/webgpu/**/*.ts'
    ]);
    fullReport += perfResults;

    const memoryResults = await runAgent('Memory', MEMORY_PROMPT, [
      'packages/reasoning/**/*.ts',
      'packages/core/src/memory/**/*.ts'
    ]);
    fullReport += memoryResults;

    const outputPath = path.join(process.cwd(), 'optimization_recommendations.md');
    await fs.writeFile(outputPath, fullReport, 'utf-8');
    
    console.log(`\n✅ Optimization complete! Report saved to ${outputPath}`);
  } catch (error) {
    console.error('❌ Error during optimization:', error);
  }
}

main().catch(console.error);
