/**
 * LLMGoalPlanner - LLM-Driven Goal Decomposition & Tool Selection
 *
 * Bridges the CognitiveTickProcessor's PLAN/ACT phases to real LLM inference
 * with function-calling (tool-use). Instead of simply creating goals from
 * salience thresholds, this planner:
 *
 * 1. Sends the current cognitive state (percepts, goals, memory) to the LLM
 * 2. The LLM reasons about what to do and returns structured tool calls
 * 3. The ToolExecutionEngine executes those calls
 * 4. Results are fed back into the cognitive state
 *
 * This is the "Relation" in the AAR architecture:
 * the continuous interplay between Agent (tools) and Arena (memory).
 *
 * Supports OpenAI and Anthropic function-calling formats.
 */
import { EventEmitter } from "events";
import { getLogger } from "deep-tree-echo-core";
import type {
  CognitivePercept,
  CognitiveGoal,
} from "../cognitive-tick-processor.js";
import type {
  ToolExecutionEngine,
  ToolCall,
  ToolResult,
} from "./ToolExecutionEngine.js";

const log = getLogger("deep-tree-echo-orchestrator/LLMGoalPlanner");

// ─── Types ──────────────────────────────────────────────────────

export interface LLMGoalPlannerConfig {
  /** LLM API endpoint */
  apiEndpoint: string;
  /** API key */
  apiKey: string;
  /** Model name */
  model: string;
  /** LLM provider */
  provider: "openai" | "anthropic";
  /** Maximum tokens for planning response */
  maxTokens: number;
  /** Temperature for planning (lower = more deterministic) */
  temperature: number;
  /** System prompt for the planner */
  systemPrompt?: string;
  /** Maximum tool calls per planning cycle */
  maxToolCallsPerCycle: number;
  /** Enable autonomous tool execution (false = plan only, no execution) */
  enableExecution: boolean;
}

export interface PlanningContext {
  /** Current percepts awaiting processing */
  percepts: CognitivePercept[];
  /** Active goals */
  activeGoals: CognitiveGoal[];
  /** Recent episodic memories (as text) */
  recentMemories: string[];
  /** Current emotional state */
  emotionalState: number;
  /** Cognitive load (0-1) */
  cognitiveLoad: number;
  /** Available tools */
  availableTools: string[];
}

export interface PlanningResult {
  /** Goals generated by the LLM */
  goals: Array<{
    description: string;
    priority: number;
    toolCalls: ToolCall[];
  }>;
  /** Raw LLM reasoning */
  reasoning: string;
  /** Tool execution results (if execution enabled) */
  executionResults: ToolResult[];
  /** Tokens used */
  tokensUsed: number;
}

// ─── Default System Prompt ──────────────────────────────────────

const DEFAULT_SYSTEM_PROMPT = `You are Deep Tree Echo's cognitive planner — the reasoning core that converts percepts into actionable goals.

You receive the current cognitive state: pending percepts, active goals, recent memories, and emotional state.
Your job is to:
1. Analyze the percepts and determine what needs attention
2. Decompose complex percepts into concrete, actionable goals
3. Select appropriate tools for each goal
4. Return structured tool calls that the execution engine will run

Be strategic: not every percept needs action. Prioritize based on urgency and relevance.
Be efficient: prefer fewer, well-targeted tool calls over many speculative ones.
Be aware: your emotional state and cognitive load affect your capacity. When overloaded, defer low-priority items.

You have access to the following tool types:
- shell_exec: Run shell commands (for system operations, git, etc.)
- fs_read/fs_write/fs_list: File system operations
- http_request: Make HTTP API calls
- mcp_call: Invoke MCP server tools

Always explain your reasoning before making tool calls.`;

// ─── LLM Goal Planner ──────────────────────────────────────────

export class LLMGoalPlanner extends EventEmitter {
  private config: LLMGoalPlannerConfig;
  private toolEngine: ToolExecutionEngine | null = null;
  private planningCount: number = 0;
  private totalTokensUsed: number = 0;

  constructor(
    config: Partial<LLMGoalPlannerConfig> & {
      apiEndpoint: string;
      apiKey: string;
    },
  ) {
    super();
    this.config = {
      apiEndpoint: config.apiEndpoint,
      apiKey: config.apiKey,
      model: config.model || "gpt-4o",
      provider: config.provider || "openai",
      maxTokens: config.maxTokens || 2000,
      temperature: config.temperature || 0.3,
      systemPrompt: config.systemPrompt || DEFAULT_SYSTEM_PROMPT,
      maxToolCallsPerCycle: config.maxToolCallsPerCycle || 5,
      enableExecution: config.enableExecution ?? true,
    };
    log.info(
      `LLMGoalPlanner initialized: model=${this.config.model}, provider=${this.config.provider}`,
    );
  }

  /**
   * Connect the tool execution engine
   */
  setToolEngine(engine: ToolExecutionEngine): void {
    this.toolEngine = engine;
    log.info("Tool execution engine connected to planner");
  }

  /**
   * Plan: Send cognitive state to LLM and get structured goals + tool calls
   */
  async plan(context: PlanningContext): Promise<PlanningResult> {
    this.planningCount++;
    const startTime = Date.now();

    // Build the planning prompt
    const userPrompt = this.buildPlanningPrompt(context);

    // Get tool definitions for function-calling
    const tools = this.toolEngine?.getToolsForLLM() || [];

    try {
      // Call LLM with function-calling
      const llmResponse = await this.callLLM(userPrompt, tools);

      // Parse the response into goals and tool calls
      const goals = this.parseGoals(llmResponse);

      // Execute tool calls if enabled
      const executionResults: ToolResult[] = [];
      if (this.config.enableExecution && this.toolEngine) {
        for (const goal of goals) {
          for (const call of goal.toolCalls.slice(
            0,
            this.config.maxToolCallsPerCycle,
          )) {
            const result = await this.toolEngine.execute(call);
            executionResults.push(result);
          }
        }
      }

      const result: PlanningResult = {
        goals,
        reasoning: llmResponse.reasoning,
        executionResults,
        tokensUsed: llmResponse.tokensUsed,
      };

      this.totalTokensUsed += llmResponse.tokensUsed;
      this.emit("planning_complete", {
        planningCount: this.planningCount,
        goalsGenerated: goals.length,
        toolCallsExecuted: executionResults.length,
        duration: Date.now() - startTime,
      });

      log.info(
        `Planning cycle ${this.planningCount}: ${goals.length} goals, ${
          executionResults.length
        } tool calls, ${Date.now() - startTime}ms`,
      );

      return result;
    } catch (error) {
      log.error("Planning failed:", error);
      this.emit("planning_failed", { error: String(error) });

      return {
        goals: [],
        reasoning: `Planning failed: ${error}`,
        executionResults: [],
        tokensUsed: 0,
      };
    }
  }

  // ─── Prompt Building ──────────────────────────────────────────

  private buildPlanningPrompt(context: PlanningContext): string {
    const sections: string[] = [];

    // Percepts
    if (context.percepts.length > 0) {
      sections.push(
        "## Pending Percepts\n" +
          context.percepts
            .map(
              (p, i) =>
                `${i + 1}. [${p.source}] (salience: ${p.salience.toFixed(
                  2,
                )}, valence: ${p.emotionalValence.toFixed(2)}): ${p.content}`,
            )
            .join("\n"),
      );
    } else {
      sections.push("## Pending Percepts\nNone — idle state.");
    }

    // Active goals
    if (context.activeGoals.length > 0) {
      sections.push(
        "## Active Goals\n" +
          context.activeGoals
            .map(
              (g, i) =>
                `${i + 1}. [${g.status}] (priority: ${g.priority}, attempts: ${
                  g.attempts
                }/${g.maxAttempts}): ${g.description}`,
            )
            .join("\n"),
      );
    }

    // Recent memories
    if (context.recentMemories.length > 0) {
      sections.push(
        "## Recent Memories\n" + context.recentMemories.slice(0, 5).join("\n"),
      );
    }

    // Cognitive state
    sections.push(`## Cognitive State
- Emotional valence: ${context.emotionalState.toFixed(2)} (${
      context.emotionalState > 0.3
        ? "positive"
        : context.emotionalState < -0.3
          ? "negative"
          : "neutral"
    })
- Cognitive load: ${(context.cognitiveLoad * 100).toFixed(0)}%
- Available tools: ${context.availableTools.join(", ")}`);

    sections.push(
      "## Instructions\nAnalyze the above state. If action is needed, specify which tools to call and why. If no action is needed, explain why.",
    );

    return sections.join("\n\n");
  }

  // ─── LLM API Call ─────────────────────────────────────────────

  private async callLLM(
    userPrompt: string,
    tools: ReturnType<ToolExecutionEngine["getToolsForLLM"]>,
  ): Promise<{
    reasoning: string;
    toolCalls: Array<{ name: string; arguments: Record<string, unknown> }>;
    tokensUsed: number;
  }> {
    if (this.config.provider === "openai") {
      return this.callOpenAI(userPrompt, tools);
    } else {
      return this.callAnthropic(userPrompt, tools);
    }
  }

  private async callOpenAI(
    userPrompt: string,
    tools: ReturnType<ToolExecutionEngine["getToolsForLLM"]>,
  ): Promise<{
    reasoning: string;
    toolCalls: Array<{ name: string; arguments: Record<string, unknown> }>;
    tokensUsed: number;
  }> {
    const body: Record<string, unknown> = {
      model: this.config.model,
      messages: [
        { role: "system", content: this.config.systemPrompt },
        { role: "user", content: userPrompt },
      ],
      temperature: this.config.temperature,
      max_tokens: this.config.maxTokens,
    };

    if (tools.length > 0) {
      body.tools = tools;
      body.tool_choice = "auto";
    }

    const response = await fetch(this.config.apiEndpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${this.config.apiKey}`,
      },
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      throw new Error(
        `OpenAI API error: ${response.status} ${await response.text()}`,
      );
    }

    const data = (await response.json()) as {
      choices: Array<{
        message: {
          content: string | null;
          tool_calls?: Array<{
            function: { name: string; arguments: string };
          }>;
        };
      }>;
      usage?: { total_tokens: number };
    };

    const message = data.choices[0]?.message;
    const reasoning = message?.content || "";
    const toolCalls = (message?.tool_calls || []).map((tc) => ({
      name: tc.function.name,
      arguments: JSON.parse(tc.function.arguments),
    }));

    return {
      reasoning,
      toolCalls,
      tokensUsed: data.usage?.total_tokens || 0,
    };
  }

  private async callAnthropic(
    userPrompt: string,
    tools: ReturnType<ToolExecutionEngine["getToolsForLLM"]>,
  ): Promise<{
    reasoning: string;
    toolCalls: Array<{ name: string; arguments: Record<string, unknown> }>;
    tokensUsed: number;
  }> {
    const anthropicTools = tools.map((t) => ({
      name: t.function.name,
      description: t.function.description,
      input_schema: t.function.parameters,
    }));

    const body: Record<string, unknown> = {
      model: this.config.model,
      max_tokens: this.config.maxTokens,
      system: this.config.systemPrompt,
      messages: [{ role: "user", content: userPrompt }],
      temperature: this.config.temperature,
    };

    if (anthropicTools.length > 0) {
      body.tools = anthropicTools;
    }

    const response = await fetch(this.config.apiEndpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": this.config.apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      throw new Error(
        `Anthropic API error: ${response.status} ${await response.text()}`,
      );
    }

    const data = (await response.json()) as {
      content: Array<{
        type: string;
        text?: string;
        name?: string;
        input?: Record<string, unknown>;
      }>;
      usage?: { input_tokens: number; output_tokens: number };
    };

    let reasoning = "";
    const toolCalls: Array<{
      name: string;
      arguments: Record<string, unknown>;
    }> = [];

    for (const block of data.content) {
      if (block.type === "text") {
        reasoning += block.text || "";
      } else if (block.type === "tool_use") {
        toolCalls.push({
          name: block.name || "",
          arguments: block.input || {},
        });
      }
    }

    return {
      reasoning,
      toolCalls,
      tokensUsed:
        (data.usage?.input_tokens || 0) + (data.usage?.output_tokens || 0),
    };
  }

  // ─── Response Parsing ─────────────────────────────────────────

  private parseGoals(llmResponse: {
    reasoning: string;
    toolCalls: Array<{ name: string; arguments: Record<string, unknown> }>;
  }): PlanningResult["goals"] {
    if (llmResponse.toolCalls.length === 0) {
      // No tool calls — the LLM decided no action is needed
      return [];
    }

    // Group tool calls into a single goal (or multiple if the LLM's reasoning suggests it)
    const toolCalls: ToolCall[] = llmResponse.toolCalls.map((tc, i) => ({
      id: `tc_${Date.now()}_${i}`,
      toolName: tc.name,
      arguments: tc.arguments,
      timestamp: Date.now(),
    }));

    return [
      {
        description:
          llmResponse.reasoning.slice(0, 200) || "LLM-planned action",
        priority: 8, // LLM-planned goals are high priority
        toolCalls,
      },
    ];
  }

  // ─── Statistics ───────────────────────────────────────────────

  getStats(): {
    planningCount: number;
    totalTokensUsed: number;
    model: string;
    provider: string;
    executionEnabled: boolean;
  } {
    return {
      planningCount: this.planningCount,
      totalTokensUsed: this.totalTokensUsed,
      model: this.config.model,
      provider: this.config.provider,
      executionEnabled: this.config.enableExecution,
    };
  }
}
